

# 2018 data
llpNanoAOD_v2:
  path: root://xcache//store/group/lpcmetx/SIDM/Data/2018data/NanoAOD/DoubleMuon/
  samples:
    DoubleMuon_2018C:
      files:
      - output_1.root
      - output_10.root
      - output_100.root
      - output_101.root
      - output_102.root
      - output_103.root
      - output_104.root
      - output_105.root
      - output_106.root
      - output_107.root
      - output_108.root
      - output_109.root
      - output_11.root
      - output_110.root
      - output_111.root
      - output_112.root
      - output_113.root
      - output_114.root
      - output_115.root
      - output_116.root
      - output_117.root
      - output_118.root
      - output_119.root
      - output_12.root
      - output_120.root
      - output_121.root
      - output_122.root
      - output_123.root
      - output_124.root
      - output_125.root
      - output_126.root
      - output_127.root
      - output_128.root
      - output_129.root
      - output_13.root
      - output_130.root
      - output_131.root
      - output_132.root
      - output_133.root
      - output_134.root
      - output_135.root
      - output_136.root
      - output_137.root
      - output_138.root
      - output_139.root
      - output_14.root
      - output_140.root
      - output_141.root
      - output_142.root
      - output_143.root
      - output_144.root
      - output_145.root
      - output_146.root
      - output_147.root
      - output_148.root
      - output_149.root
      - output_15.root
      - output_150.root
      - output_151.root
      - output_152.root
      - output_153.root
      - output_154.root
      - output_155.root
      - output_156.root
      - output_157.root
      - output_158.root
      - output_159.root
      - output_16.root
      - output_160.root
      - output_161.root
      - output_162.root
      - output_163.root
      - output_164.root
      - output_165.root
      - output_166.root
      - output_167.root
      - output_168.root
      - output_169.root
      - output_17.root
      - output_170.root
      - output_171.root
      - output_172.root
      - output_173.root
      - output_174.root
      - output_175.root
      - output_176.root
      - output_177.root
      - output_178.root
      - output_179.root
      - output_18.root
      - output_180.root
      - output_181.root
      - output_182.root
      - output_183.root
      - output_184.root
      - output_185.root
      - output_186.root
      - output_187.root
      - output_188.root
      - output_189.root
      - output_19.root
      - output_190.root
      - output_191.root
      - output_192.root
      - output_193.root
      - output_194.root
      - output_195.root
      - output_196.root
      - output_197.root
      - output_198.root
      - output_199.root
      - output_2.root
      - output_20.root
      - output_200.root
      - output_201.root
      - output_202.root
      - output_203.root
      - output_204.root
      - output_205.root
      - output_206.root
      - output_207.root
      - output_208.root
      - output_209.root
      - output_21.root
      - output_210.root
      - output_211.root
      - output_212.root
      - output_213.root
      - output_214.root
      - output_215.root
      - output_216.root
      - output_217.root
      - output_218.root
      - output_219.root
      - output_22.root
      - output_220.root
      - output_221.root
      - output_222.root
      - output_223.root
      - output_224.root
      - output_225.root
      - output_226.root
      - output_227.root
      - output_228.root
      - output_229.root
      - output_23.root
      - output_230.root
      - output_231.root
      - output_232.root
      - output_233.root
      - output_234.root
      - output_235.root
      - output_236.root
      - output_237.root
      - output_238.root
      - output_239.root
      - output_24.root
      - output_240.root
      - output_241.root
      - output_242.root
      - output_243.root
      - output_244.root
      - output_245.root
      - output_246.root
      - output_247.root
      - output_248.root
      - output_249.root
      - output_25.root
      - output_250.root
      - output_251.root
      - output_252.root
      - output_253.root
      - output_254.root
      - output_255.root
      - output_256.root
      - output_257.root
      - output_258.root
      - output_259.root
      - output_26.root
      - output_260.root
      - output_261.root
      - output_262.root
      - output_263.root
      - output_264.root
      - output_265.root
      - output_266.root
      - output_267.root
      - output_268.root
      - output_269.root
      - output_27.root
      - output_270.root
      - output_271.root
      - output_272.root
      - output_273.root
      - output_274.root
      - output_275.root
      - output_276.root
      - output_277.root
      - output_278.root
      - output_279.root
      - output_28.root
      - output_280.root
      - output_281.root
      - output_282.root
      - output_283.root
      - output_284.root
      - output_285.root
      - output_286.root
      - output_287.root
      - output_288.root
      - output_289.root
      - output_29.root
      - output_290.root
      - output_291.root
      - output_292.root
      - output_293.root
      - output_294.root
      - output_295.root
      - output_296.root
      - output_297.root
      - output_298.root
      - output_299.root
      - output_3.root
      - output_30.root
      - output_300.root
      - output_301.root
      - output_302.root
      - output_303.root
      - output_304.root
      - output_305.root
      - output_306.root
      - output_307.root
      - output_308.root
      - output_309.root
      - output_31.root
      - output_310.root
      - output_311.root
      - output_312.root
      - output_313.root
      - output_314.root
      - output_315.root
      - output_316.root
      - output_317.root
      - output_318.root
      - output_319.root
      - output_32.root
      - output_320.root
      - output_321.root
      - output_322.root
      - output_323.root
      - output_324.root
      - output_325.root
      - output_326.root
      - output_327.root
      - output_328.root
      - output_329.root
      - output_33.root
      - output_330.root
      - output_331.root
      - output_332.root
      - output_333.root
      - output_334.root
      - output_335.root
      - output_336.root
      - output_337.root
      - output_338.root
      - output_339.root
      - output_34.root
      - output_340.root
      - output_341.root
      - output_342.root
      - output_343.root
      - output_344.root
      - output_345.root
      - output_346.root
      - output_347.root
      - output_348.root
      - output_349.root
      - output_35.root
      - output_350.root
      - output_351.root
      - output_352.root
      - output_353.root
      - output_354.root
      - output_355.root
      - output_356.root
      - output_357.root
      - output_358.root
      - output_359.root
      - output_36.root
      - output_360.root
      - output_361.root
      - output_362.root
      - output_363.root
      - output_364.root
      - output_365.root
      - output_366.root
      - output_367.root
      - output_368.root
      - output_369.root
      - output_37.root
      - output_370.root
      - output_371.root
      - output_372.root
      - output_373.root
      - output_374.root
      - output_375.root
      - output_376.root
      - output_377.root
      - output_378.root
      - output_379.root
      - output_38.root
      - output_380.root
      - output_381.root
      - output_382.root
      - output_383.root
      - output_384.root
      - output_385.root
      - output_386.root
      - output_387.root
      - output_388.root
      - output_389.root
      - output_39.root
      - output_390.root
      - output_391.root
      - output_392.root
      - output_393.root
      - output_394.root
      - output_395.root
      - output_396.root
      - output_397.root
      - output_398.root
      - output_399.root
      - output_4.root
      - output_40.root
      - output_400.root
      - output_401.root
      - output_402.root
      - output_403.root
      - output_404.root
      - output_405.root
      - output_406.root
      - output_407.root
      - output_408.root
      - output_409.root
      - output_41.root
      - output_410.root
      - output_411.root
      - output_412.root
      - output_413.root
      - output_414.root
      - output_415.root
      - output_416.root
      - output_417.root
      - output_418.root
      - output_419.root
      - output_42.root
      - output_420.root
      - output_421.root
      - output_422.root
      - output_423.root
      - output_424.root
      - output_425.root
      - output_426.root
      - output_427.root
      - output_428.root
      - output_429.root
      - output_43.root
      - output_430.root
      - output_431.root
      - output_432.root
      - output_433.root
      - output_434.root
      - output_435.root
      - output_436.root
      - output_437.root
      - output_438.root
      - output_439.root
      - output_44.root
      - output_440.root
      - output_441.root
      - output_442.root
      - output_443.root
      - output_444.root
      - output_445.root
      - output_446.root
      - output_447.root
      - output_448.root
      - output_449.root
      - output_45.root
      - output_450.root
      - output_451.root
      - output_452.root
      - output_453.root
      - output_454.root
      - output_455.root
      - output_456.root
      - output_457.root
      - output_458.root
      - output_459.root
      - output_46.root
      - output_460.root
      - output_461.root
      - output_462.root
      - output_463.root
      - output_464.root
      - output_465.root
      - output_466.root
      - output_467.root
      - output_468.root
      - output_469.root
      - output_47.root
      - output_470.root
      - output_471.root
      - output_472.root
      - output_473.root
      - output_474.root
      - output_475.root
      - output_476.root
      - output_477.root
      - output_478.root
      - output_479.root
      - output_48.root
      - output_480.root
      - output_481.root
      - output_482.root
      - output_483.root
      - output_484.root
      - output_485.root
      - output_486.root
      - output_487.root
      - output_488.root
      - output_489.root
      - output_49.root
      - output_490.root
      - output_491.root
      - output_492.root
      - output_493.root
      - output_494.root
      - output_495.root
      - output_496.root
      - output_497.root
      - output_498.root
      - output_499.root
      - output_5.root
      - output_50.root
      - output_500.root
      - output_501.root
      - output_502.root
      - output_503.root
      - output_504.root
      - output_505.root
      - output_506.root
      - output_507.root
      - output_508.root
      - output_509.root
      - output_51.root
      - output_510.root
      - output_511.root
      - output_512.root
      - output_513.root
      - output_514.root
      - output_515.root
      - output_516.root
      - output_517.root
      - output_518.root
      - output_519.root
      - output_52.root
      - output_520.root
      - output_521.root
      - output_522.root
      - output_523.root
      - output_524.root
      - output_525.root
      - output_526.root
      - output_527.root
      - output_528.root
      - output_529.root
      - output_53.root
      - output_530.root
      - output_531.root
      - output_532.root
      - output_533.root
      - output_534.root
      - output_535.root
      - output_536.root
      - output_537.root
      - output_538.root
      - output_539.root
      - output_54.root
      - output_540.root
      - output_541.root
      - output_542.root
      - output_543.root
      - output_544.root
      - output_545.root
      - output_546.root
      - output_547.root
      - output_548.root
      - output_549.root
      - output_55.root
      - output_550.root
      - output_551.root
      - output_552.root
      - output_553.root
      - output_554.root
      - output_555.root
      - output_556.root
      - output_557.root
      - output_558.root
      - output_559.root
      - output_56.root
      - output_560.root
      - output_561.root
      - output_562.root
      - output_563.root
      - output_564.root
      - output_565.root
      - output_566.root
      - output_567.root
      - output_568.root
      - output_569.root
      - output_57.root
      - output_570.root
      - output_571.root
      - output_572.root
      - output_573.root
      - output_574.root
      - output_575.root
      - output_576.root
      - output_577.root
      - output_578.root
      - output_579.root
      - output_58.root
      - output_580.root
      - output_581.root
      - output_582.root
      - output_583.root
      - output_584.root
      - output_585.root
      - output_586.root
      - output_587.root
      - output_588.root
      - output_589.root
      - output_59.root
      - output_590.root
      - output_591.root
      - output_592.root
      - output_593.root
      - output_594.root
      - output_595.root
      - output_596.root
      - output_597.root
      - output_598.root
      - output_599.root
      - output_6.root
      - output_60.root
      - output_601.root
      - output_602.root
      - output_603.root
      - output_604.root
      - output_605.root
      - output_606.root
      - output_607.root
      - output_608.root
      - output_609.root
      - output_61.root
      - output_610.root
      - output_611.root
      - output_612.root
      - output_613.root
      - output_614.root
      - output_615.root
      - output_616.root
      - output_617.root
      - output_618.root
      - output_619.root
      - output_62.root
      - output_620.root
      - output_621.root
      - output_622.root
      - output_623.root
      - output_624.root
      - output_625.root
      - output_626.root
      - output_627.root
      - output_628.root
      - output_629.root
      - output_63.root
      - output_630.root
      - output_631.root
      - output_632.root
      - output_633.root
      - output_634.root
      - output_635.root
      - output_636.root
      - output_637.root
      - output_64.root
      - output_65.root
      - output_66.root
      - output_67.root
      - output_68.root
      - output_69.root
      - output_7.root
      - output_70.root
      - output_71.root
      - output_72.root
      - output_73.root
      - output_74.root
      - output_75.root
      - output_76.root
      - output_77.root
      - output_78.root
      - output_79.root
      - output_8.root
      - output_80.root
      - output_81.root
      - output_82.root
      - output_83.root
      - output_84.root
      - output_85.root
      - output_86.root
      - output_87.root
      - output_88.root
      - output_89.root
      - output_9.root
      - output_90.root
      - output_91.root
      - output_92.root
      - output_93.root
      - output_94.root
      - output_95.root
      - output_96.root
      - output_97.root
      - output_98.root
      - output_99.root
      is_data: true
      path: LLPnanoAODv1_Run2018C-15Feb2022_UL2018-v1/251125_125646/0000/
      skim_factor: 1.0
      year: "2018"

